server:
  port: 8080
  servlet:
    context-path: /api-gateway
spring:
  cloud:
    gateway:
      routes:
        - id: CatalogRoute
          uri: lb://catalog-service
          predicates:
            - Path=/api-catalog/**
        - id: MovieRoute
          uri: lb://movie-service
          predicates:
            - Path=/api-movie/**
        - id: SerieRoute
          uri: lb://serie-service
          predicates:
            - Path=/api-serie/**
        - id: GatewayRoute
          uri: lb://API-GATEWAY
          predicates:
            - Path=/api-gateway/**
