server:
  port: ${PORT:8080}
  servlet:
    context-path: /gateway-api
spring:
  cloud:
    gateway:
      routes:
        - id: CatalogRoute
          uri: lb://catalog-service
          predicates:
            - Path=/catalog-api/**
        - id: MovieRoute
          uri: lb://movie-service
          predicates:
            - Path=/movie-api/**
          filters:
            - name: CircuitBreaker
              args:
                name: movie-service
                fallbackUri: forward:/movie-fallback/moviePostFallback
        - id: GatewayRoute
          uri: lb://API-GATEWAY
          predicates:
            - Path=/gateway-api/**
