eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/ # http://eureka-server:5000/eureka/
spring:
  zipkin:
    base-url: http://localhost:9411/ # http://zipkin:9411/
  rabbitmq:
    username: guest
    password: guest
    host: localhost # rabbitmq
    port: 5672
  health:
    circuitBreaker:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
info:
  author: Belicio Batista Cardoso
  mail: belloinfo@gmail.com
server:
  port: ${PORT:9999}

## Resilience4J configs for CircuitBreaker Pattern
resilience4j:
  circuitbreaker:
    configs:
      default:
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
    instances:
      movie-service:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failueRateThreshold: 50
        waitDurationInOpenState: 50s
        permittedNumberOfCalssInHalfOpenState: 2
        automaticTransitionFromOpenToHalfIfOpenEnabled: true
      api-gateway:
        baseConfig: default

queue:
  mail: queue-mail
  insert: queue-insert
  movie-insert: queue-insert-movie
  movie-update: queue-update-movie
  serie-insert: queue-insert-serie
  season-insert: queue-insert-season
  chapter-insert: queue-insert-chapter
