eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  health:
    circuitBreaker:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
info:
  author: Belicio Batista Cardoso
  mail: belloinfo@gmail.com
server:
  port: ${PORT:9999}

## Resilience4J configs for CircuitBreaker Pattern
resilience4j:
  circuitbreaker:
    instances:
      movie-service:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failueRateThreshold: 50
        waitDurationInOpenState: 50s
        permittedNumberOfCalssInHalfOpenState: 2
        automaticTransitionFromOpenToHalfIfOpenEnabled: true
